spring:
  datasource:
    url: jdbc:mysql://localhost:3307/car_stock_list
    username: root
    password: dockertest2
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:  
  mapper-locations: classpath*:/db/*.xml 